---
# tasks file for ansible-role-squid/

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: "Install packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ squid_packages }}"
  when: item|string not in ansible_facts.packages

- name: "Configure service configuration file"
  ansible.builtin.lineinfile:
    dest: "{{ squid_config }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backup: yes
  with_items:
    - regexp: "^http_port"
      line: "http_port {{ squid_port }}"
    - regexp: "^#http_access allow localnet"
      line: "http_access allow localnet"

- name: "Enable & start daemon service"
  ansible.builtin.service:
    name: "{{ squid_service }}"
    enabled: yes
    state: restarted
